(function(){'use strict';
var I=window.INK=window.INK||{};var C=document.getElementById('game'),G=C.getContext('2d'),BOOT=document.getElementById('boot');if(!G){BOOT.textContent='Canvas 2D unavailable';return}
window.onerror=function(m,s,l,c){BOOT.style.display='block';BOOT.textContent='JS error: '+m+' @ '+l+':'+c};
var W=0,H=0,D=1,LAST=0,first=true,seed=(Date.now()^0x7f31ac9)>>>0;I.t=0;
function resize(){D=Math.max(1,Math.min(2,window.devicePixelRatio||1));W=Math.max(320,window.innerWidth||320);H=Math.max(320,window.innerHeight||320);C.width=Math.round(W*D);C.height=Math.round(H*D);C.style.width=W+'px';C.style.height=H+'px';G.setTransform(D,0,0,D,0,0)}addEventListener('resize',resize,{passive:true});resize();
I.RNG=function(s){this.s=s>>>0};I.RNG.prototype.n=function(){this.s=(Math.imul(this.s,1664525)+1013904223)>>>0;return this.s/4294967296};I.RNG.prototype.r=function(a,b){return a+(b-a)*this.n()};I.RNG.prototype.i=function(a,b){return Math.floor(this.r(a,b+1))};I.RNG.prototype.p=function(a){return a[this.i(0,a.length-1)]};
function clamp(v,a,b){return v<a?a:v>b?b:v}function lerp(a,b,t){return a+(b-a)*t}function hypot(x,y){return Math.sqrt(x*x+y*y)}function rr(x,y,w,h,r){I.rr(G,x,y,w,h,r)}
var rng=new I.RNG(seed),stars=[],rocks=[],planets=[],traffic=[],mode='space',landed=null,transition=0,near=null,lastAction=false;
var player={x:0,y:0,vx:0,vy:0,a:-.2,bank:0,ox:0,oy:0,d:null};
function planetDNA(s,type){var q=new I.RNG(s),names=type===0?['Verdania','Nymora','Pelagos']:type===1?['Rusthollow','Dustmere','Kharra']:['Glacia','Borealis','Cryonn'];return{seed:s,type:type,name:q.p(names),r:q.r(46,68)}}
function build(){rng=new I.RNG(seed);stars.length=rocks.length=traffic.length=0;for(var i=0;i<180;i++)stars.push({x:rng.r(-1900,1900),y:rng.r(-1500,1500),z:rng.r(.3,1),r:rng.r(.6,1.8)});for(i=0;i<28;i++)rocks.push({x:rng.r(-1400,1400),y:rng.r(-1100,1100),d:I.rockDNA(seed+i*991)});planets=[planetDNA(seed+100,0),planetDNA(seed+200,1),planetDNA(seed+300,2)];var cc=[[330,-90],[-650,420],[850,310]];for(i=0;i<3;i++){planets[i].x=cc[i][0];planets[i].y=cc[i][1]}for(i=0;i<4;i++)traffic.push({x:rng.r(-700,700),y:rng.r(-550,550),a:rng.r(0,6.28),v:rng.r(24,44),d:I.shipDNA(seed+700+i*81)});player.x=player.y=player.vx=player.vy=0;player.a=-.2;player.d=I.shipDNA(seed^0x87aac35)}build();
var key={},joy={on:false,id:null,sx:0,sy:0,x:0,y:0},touchBoost=false,touchAction=false;
addEventListener('keydown',function(e){key[e.key.toLowerCase()]=true;if(e.key===' '||e.key.indexOf('Arrow')===0)e.preventDefault()});addEventListener('keyup',function(e){key[e.key.toLowerCase()]=false});
function ui(){var r=Math.min(W,H)*.115;return{joy:{x:18+r,y:H-18-r,r:r},boost:{x:W-102,y:H-74,w:84,h:52},act:{x:W-112,y:H-140,w:94,h:46}}}function inside(x,y,b){return x>=b.x&&y>=b.y&&x<=b.x+b.w&&y<=b.y+b.h}
C.addEventListener('touchstart',function(e){e.preventDefault();var U=ui();for(var i=0;i<e.changedTouches.length;i++){var t=e.changedTouches[i],x=t.clientX,y=t.clientY;if(inside(x,y,U.boost)){touchBoost=true;continue}if(inside(x,y,U.act)){touchAction=true;continue}if(!joy.on&&x<W*.58)joy={on:true,id:t.identifier,sx:x,sy:y,x:x,y:y}}},{passive:false});
C.addEventListener('touchmove',function(e){e.preventDefault();for(var i=0;i<e.changedTouches.length;i++){var t=e.changedTouches[i];if(joy.on&&t.identifier===joy.id){joy.x=t.clientX;joy.y=t.clientY}}},{passive:false});
function tend(e){e.preventDefault();for(var i=0;i<e.changedTouches.length;i++){var t=e.changedTouches[i];if(joy.on&&t.identifier===joy.id)joy.on=false}touchBoost=false;touchAction=false}C.addEventListener('touchend',tend,{passive:false});C.addEventListener('touchcancel',function(){joy.on=false;touchBoost=false;touchAction=false},{passive:false});
function controls(){var turn=0,th=0,boost=touchBoost||!!key.shift||!!key[' '],action=touchAction||!!key.e;if(key.a||key.arrowleft)turn--;if(key.d||key.arrowright)turn++;if(key.w||key.arrowup)th++;if(key.s||key.arrowdown)th-=.5;if(joy.on){var dx=joy.x-joy.sx,dy=joy.y-joy.sy,mx=Math.min(W,H)*.10,m=Math.min(mx,hypot(dx,dy)),a=Math.atan2(dy,dx);turn+=Math.cos(a)*m/mx;th+=-Math.sin(a)*m/mx}return{turn:clamp(turn,-1,1),th:clamp(th,-1,1),boost:boost,action:action}}
function sx(x){return x-player.x+W/2}function sy(y){return y-player.y+H/2}
function update(dt){var c=controls(),acc=c.boost?175:105;player.a+=c.turn*2.45*dt;player.vx+=Math.cos(player.a)*c.th*acc*dt;player.vy+=Math.sin(player.a)*c.th*acc*dt;player.vx*=Math.pow(.985,dt*60);player.vy*=Math.pow(.985,dt*60);var sp=hypot(player.vx,player.vy),mx=c.boost?250:175;if(sp>mx){player.vx*=mx/sp;player.vy*=mx/sp}if(mode==='space'){player.x+=player.vx*dt;player.y+=player.vy*dt}player.bank=lerp(player.bank,c.turn,.10);player.ox=lerp(player.ox,-player.vx*.035+c.turn*5,.09);player.oy=lerp(player.oy,-player.vy*.035,.09);near=null;for(var i=0;i<rocks.length;i++){var R=rocks[i];R.d.rot+=R.d.spin*dt;if(mode==='space'){var dx=player.x-R.x,dy=player.y-R.y,di=hypot(dx,dy),md=R.d.r+16;if(di<md&&di>.01){player.x+=dx/di*(md-di);player.y+=dy/di*(md-di);player.vx+=dx/di*18;player.vy+=dy/di*18}}}for(i=0;i<planets.length;i++){var p=planets[i];if(hypot(player.x-p.x,player.y-p.y)<p.r+105)near=p}for(i=0;i<traffic.length;i++){var n=traffic[i];n.a+=Math.sin(I.t*.6+i)*.09*dt;n.x+=Math.cos(n.a)*n.v*dt;n.y+=Math.sin(n.a)*n.v*dt;if(hypot(n.x,n.y)>950)n.a+=Math.PI}var pressed=c.action&&!lastAction;if(pressed){if(mode==='space'&&near){landed=near;mode='landing';transition=0}else if(mode==='landed'){mode='launch';transition=1}}lastAction=c.action;if(mode==='landing'){transition+=dt*1.7;if(transition>=1){transition=1;mode='landed'}}else if(mode==='launch'){transition-=dt*1.7;if(transition<=0){transition=0;mode='space';landed=null}}}
function bg(){var q=new I.RNG(seed^0x773311);G.fillStyle='#070912';G.fillRect(0,0,W,H);for(var n=0;n<4;n++){var nx=(q.r(-500,500)-player.x*.13)+W/2,ny=(q.r(-360,360)-player.y*.13)+H/2,rad=q.r(230,420),col=q.p([[75,105,255],[66,205,166],[190,87,228],[244,126,93]]),gr=G.createRadialGradient(nx,ny,0,nx,ny,rad);gr.addColorStop(0,'rgba('+col.join(',')+',.09)');gr.addColorStop(1,'rgba('+col.join(',')+',0)');G.fillStyle=gr;G.beginPath();G.arc(nx,ny,rad,0,6.28);G.fill()}for(var i=0;i<stars.length;i++){var s=stars[i],x=sx(s.x*s.z),y=sy(s.y*s.z);if(x<0||y<0||x>W||y>H)continue;G.globalAlpha=.35+s.z*.6;G.fillStyle='#fff';G.fillRect(x,y,s.r,s.r)}G.globalAlpha=1}
function radar(){var r=48,x=16+r,y=16+r;G.save();G.translate(x,y);G.fillStyle='rgba(8,11,19,.72)';G.beginPath();G.arc(0,0,r,0,6.28);G.fill();G.strokeStyle='#ddecff33';G.lineWidth=1.5;G.stroke();G.beginPath();G.arc(0,0,r*.62,0,6.28);G.stroke();G.beginPath();G.moveTo(-r,0);G.lineTo(r,0);G.moveTo(0,-r);G.lineTo(0,r);G.stroke();for(var i=0;i<planets.length;i++){var p=planets[i],px=(p.x-player.x)*.055,py=(p.y-player.y)*.055;if(hypot(px,py)<r-4){G.fillStyle=p.type===0?'#62e8bb':p.type===1?'#ffbd74':'#a7d7ff';G.beginPath();G.arc(px,py,3.5,0,6.28);G.fill()}}G.rotate(player.a);G.fillStyle='#fff';G.beginPath();G.moveTo(9,0);G.lineTo(-6,4);G.lineTo(-2,0);G.lineTo(-6,-4);G.fill();G.restore()}
function hud(){var compact=W<620,panW=compact?150:224;rr(W-panW-14,14,panW,72,14);G.fillStyle='rgba(8,11,19,.72)';G.fill();G.strokeStyle='#ffffff1d';G.stroke();G.fillStyle='#f3f7ff';G.font='700 15px sans-serif';G.fillText('INKSTAR',W-panW,37);G.font='11px sans-serif';G.fillStyle='#dbe6f0cc';G.fillText(Math.round(hypot(player.vx,player.vy))+' u/s',W-panW,56);if(!compact)G.fillText('seed '+seed,W-132,56);if(near&&mode==='space'){var w=Math.min(390,W-24),x=(W-w)/2,y=H-112;rr(x,y,w,70,16);G.fillStyle='rgba(9,12,20,.88)';G.fill();G.strokeStyle='#ffffff22';G.stroke();G.fillStyle=near.type===0?'#67edbe':near.type===1?'#ffc17c':'#b7dcff';G.font='700 20px sans-serif';G.fillText(near.name,x+16,y+28);G.fillStyle='#e3ecf6cc';G.font='12px sans-serif';G.fillText('Landable · tap LAND or press E',x+16,y+49)}}
function touchUI(){if(!('ontouchstart' in window)&&W>900)return;var U=ui();G.save();G.globalAlpha=.86;G.fillStyle='#10141d72';G.strokeStyle='#ffffff2b';G.lineWidth=2;G.beginPath();G.arc(U.joy.x,U.joy.y,U.joy.r,0,6.28);G.fill();G.stroke();var kx=U.joy.x,ky=U.joy.y;if(joy.on){var dx=joy.x-joy.sx,dy=joy.y-joy.sy,m=Math.min(U.joy.r*.75,hypot(dx,dy)),a=Math.atan2(dy,dx);kx+=Math.cos(a)*m;ky+=Math.sin(a)*m}G.beginPath();G.arc(kx,ky,U.joy.r*.34,0,6.28);G.fill();G.stroke();function b(R,label){rr(R.x,R.y,R.w,R.h,13);G.fillStyle='#111620b8';G.fill();G.stroke();G.fillStyle='#fff';G.font='700 13px sans-serif';G.fillText(label,R.x+14,R.y+R.h*.62)}b(U.boost,'BOOST');b(U.act,mode==='landed'?'LAUNCH':'LAND');G.restore()}
function world(){bg();for(var i=0;i<planets.length;i++){var p=planets[i],x=sx(p.x),y=sy(p.y);if(x>-110&&y>-110&&x<W+110&&y<H+110)I.planet(G,p,x,y)}for(i=0;i<rocks.length;i++){var R=rocks[i],rx=sx(R.x),ry=sy(R.y);if(rx>-80&&ry>-80&&rx<W+80&&ry<H+80)I.rock(G,R.d,rx,ry)}for(i=0;i<traffic.length;i++){var n=traffic[i],nx=sx(n.x),ny=sy(n.y);if(nx>-80&&ny>-80&&nx<W+80&&ny<H+80)I.ship(G,n.d,nx,ny,n.a,.58,.35+.15*Math.sin(I.t*2+i),Math.sin(I.t+i)*.2)}I.ship(G,player.d,W/2+player.ox,H/2+player.oy,player.a,1,clamp(hypot(player.vx,player.vy)/170,0,1),player.bank);radar();hud();touchUI()}
function landing(){I.landscape(G,landed,W,H);G.fillStyle='rgba(4,8,15,.18)';G.fillRect(0,0,W,H);var cw=Math.min(W-24,760),ch=Math.min(142,H*.26),x=(W-cw)/2,y=H-ch-16;rr(x,y,cw,ch,20);G.fillStyle='rgba(10,14,22,.86)';G.fill();G.strokeStyle='#ffffff20';G.lineWidth=2;G.stroke();G.fillStyle=landed.type===0?'#68efc0':landed.type===1?'#ffc17c':'#b8dcff';G.font='700 '+(W<560?24:30)+'px sans-serif';G.fillText(landed.name,x+20,y+38);G.fillStyle='#e8eff7d8';G.font='13px sans-serif';G.fillText(landed.type===0?'Oceans, floating isles and humid green settlements.':landed.type===1?'Dust, salvage towers and hard orange light.':'Ice fields, aurora and a patient research outpost.',x+20,y+62);G.fillStyle='#ffffff10';rr(x+20,y+80,120,32,11);G.fill();rr(x+150,y+80,120,32,11);G.fill();G.fillStyle='#dce8f5cc';G.font='600 11px sans-serif';G.fillText(landed.type===1?'THREAT HIGH':'THREAT LOW',x+34,y+100);G.fillText(landed.type===0?'ECONOMY HIGH':'SERVICES BASIC',x+164,y+100);G.fillStyle='#fff';G.font='700 14px sans-serif';G.fillText('LANDING VISTA · tap LAUNCH or press E',x+20,y+128);touchUI();if(mode==='landing'||mode==='launch'){G.fillStyle='rgba(4,7,12,'+((1-transition)*.55)+')';G.fillRect(0,0,W,H)}}
function frame(ts){var dt=Math.min(.033,((ts-LAST)||16.7)/1000);LAST=ts;I.t+=dt;try{update(dt);if(mode==='space')world();else landing();if(first){first=false;BOOT.style.display='none'}}catch(e){BOOT.style.display='block';BOOT.textContent='Runtime error: '+(e&&e.message?e.message:e);return}requestAnimationFrame(frame)}requestAnimationFrame(frame);
})();