(function(){'use strict';
var I=window.INK=window.INK||{};
var C=document.getElementById('game'),G=C.getContext('2d'),BOOT=document.getElementById('boot');
if(!G){BOOT.textContent='Canvas 2D unavailable';return;}
window.onerror=function(m,s,l,c){BOOT.style.display='block';BOOT.textContent='JS error: '+m+' @ '+l+':'+c;};
var W=0,H=0,D=1,LAST=0,first=true,seed=(Date.now()^0x7f31ac9)>>>0;I.t=0;
function resize(){D=Math.max(1,Math.min(2,window.devicePixelRatio||1));W=Math.max(320,window.innerWidth||320);H=Math.max(320,window.innerHeight||320);C.width=Math.round(W*D);C.height=Math.round(H*D);C.style.width=W+'px';C.style.height=H+'px';G.setTransform(D,0,0,D,0,0);}
addEventListener('resize',resize,{passive:true});resize();
I.RNG=function(s){this.s=s>>>0;};
I.RNG.prototype.n=function(){this.s=(Math.imul(this.s,1664525)+1013904223)>>>0;return this.s/4294967296;};
I.RNG.prototype.r=function(a,b){return a+(b-a)*this.n();};
I.RNG.prototype.i=function(a,b){return Math.floor(this.r(a,b+1));};
I.RNG.prototype.p=function(a){return a[this.i(0,a.length-1)];};
function clamp(v,a,b){return v<a?a:v>b?b:v;}
function lerp(a,b,t){return a+(b-a)*t;}
function hypot(x,y){return Math.sqrt(x*x+y*y);}
function angleWrap(a){while(a>Math.PI)a-=Math.PI*2;while(a<-Math.PI)a+=Math.PI*2;return a;}
function rr(x,y,w,h,r){I.rr(G,x,y,w,h,r);}
var rng=new I.RNG(seed),stars=[],rocks=[],planets=[],traffic=[],mode='space',landed=null,transition=0,near=null,lastKeyAction=false;
var player={x:0,y:0,vx:0,vy:0,a:-.2,bank:0,ox:0,oy:0,d:null};
function planetDNA(s,type){var q=new I.RNG(s),names=type===0?['Verdania','Nymora','Pelagos']:type===1?['Rusthollow','Dustmere','Kharra']:['Glacia','Borealis','Cryonn'];return{seed:s,type:type,name:q.p(names),r:q.r(46,68)};}
function build(){rng=new I.RNG(seed);stars.length=rocks.length=traffic.length=0;for(var i=0;i<180;i++)stars.push({x:rng.r(-1900,1900),y:rng.r(-1500,1500),z:rng.r(.3,1),r:rng.r(.6,1.8)});for(i=0;i<28;i++)rocks.push({x:rng.r(-1400,1400),y:rng.r(-1100,1100),d:I.rockDNA(seed+i*991)});planets=[planetDNA(seed+100,0),planetDNA(seed+200,1),planetDNA(seed+300,2)];var cc=[[330,-90],[-650,420],[850,310]];for(i=0;i<3;i++){planets[i].x=cc[i][0];planets[i].y=cc[i][1];}for(i=0;i<4;i++)traffic.push({x:rng.r(-700,700),y:rng.r(-550,550),a:rng.r(0,6.28),v:rng.r(24,44),d:I.shipDNA(seed+700+i*81)});player.x=player.y=player.vx=player.vy=0;player.a=-.2;player.d=I.shipDNA(seed^0x87aac35);}
build();
var key={};
var joy={id:null,on:false,bx:0,by:0,x:0,y:0,floating:false};
var boostIds={};
var actionPulse=false;
var pointerSeen=false;
var mouseDown=false;
addEventListener('keydown',function(e){var k=e.key.toLowerCase();key[k]=true;if(k==='r'&&!e.repeat){seed=(Date.now()^((Math.random()*0xffffffff)>>>0))>>>0;build();}if(e.key===' '||e.key.indexOf('Arrow')===0)e.preventDefault();});
addEventListener('keyup',function(e){key[e.key.toLowerCase()]=false;});
function ui(){var small=Math.min(W,H),r=clamp(small*.115,42,72),bottom=28;return{joy:{x:22+r,y:H-bottom-r,r:r},boost:{x:W-110,y:H-bottom-56,w:88,h:52},act:{x:W-120,y:H-bottom-118,w:98,h:48}};}
function inside(x,y,b){return x>=b.x&&y>=b.y&&x<=b.x+b.w&&y<=b.y+b.h;}
function inCircle(x,y,c){var dx=x-c.x,dy=y-c.y;return dx*dx+dy*dy<=c.r*c.r;}
function startPointer(id,x,y){pointerSeen=true;var U=ui();if(inside(x,y,U.act)){actionPulse=true;return 'action';}if(inside(x,y,U.boost)){boostIds[id]=true;return 'boost';}if(joy.id===null&&x<W*.64){joy.id=id;joy.on=true;if(inCircle(x,y,U.joy)){joy.bx=U.joy.x;joy.by=U.joy.y;joy.floating=false;}else{joy.bx=x;joy.by=y;joy.floating=true;}joy.x=x;joy.y=y;return 'joy';}return 'none';}
function movePointer(id,x,y){if(joy.on&&joy.id===id){joy.x=x;joy.y=y;}}
function endPointer(id){if(joy.id===id){joy.id=null;joy.on=false;}if(boostIds[id])delete boostIds[id];}
if(window.PointerEvent){
 C.addEventListener('pointerdown',function(e){var role=startPointer(e.pointerId,e.clientX,e.clientY);if(role!=='none'){try{C.setPointerCapture(e.pointerId);}catch(err){}e.preventDefault();}},{passive:false});
 C.addEventListener('pointermove',function(e){movePointer(e.pointerId,e.clientX,e.clientY);if(joy.on&&joy.id===e.pointerId)e.preventDefault();},{passive:false});
 C.addEventListener('pointerup',function(e){endPointer(e.pointerId);e.preventDefault();},{passive:false});
 C.addEventListener('pointercancel',function(e){endPointer(e.pointerId);},{passive:false});
}else{
 C.addEventListener('touchstart',function(e){for(var i=0;i<e.changedTouches.length;i++){var t=e.changedTouches[i];startPointer('t'+t.identifier,t.clientX,t.clientY);}e.preventDefault();},{passive:false});
 C.addEventListener('touchmove',function(e){for(var i=0;i<e.changedTouches.length;i++){var t=e.changedTouches[i];movePointer('t'+t.identifier,t.clientX,t.clientY);}e.preventDefault();},{passive:false});
 C.addEventListener('touchend',function(e){for(var i=0;i<e.changedTouches.length;i++)endPointer('t'+e.changedTouches[i].identifier);e.preventDefault();},{passive:false});
 C.addEventListener('mousedown',function(e){mouseDown=true;startPointer('mouse',e.clientX,e.clientY);e.preventDefault();});
 addEventListener('mousemove',function(e){if(mouseDown)movePointer('mouse',e.clientX,e.clientY);});
 addEventListener('mouseup',function(){mouseDown=false;endPointer('mouse');});
}
function anyBoost(){for(var k in boostIds)if(Object.prototype.hasOwnProperty.call(boostIds,k))return true;return false;}
function controls(){var turn=0,th=0,boost=anyBoost()||!!key.shift||!!key[' '],analog=false,target=player.a,power=0;if(key.a||key.arrowleft)turn--;if(key.d||key.arrowright)turn++;if(key.w||key.arrowup)th++;if(key.s||key.arrowdown)th-=.55;if(joy.on){var dx=joy.x-joy.bx,dy=joy.y-joy.by,mx=ui().joy.r*.92,mag=Math.min(mx,hypot(dx,dy));power=clamp((mag-mx*.12)/(mx*.88),0,1);if(power>0){analog=true;target=Math.atan2(dy,dx);var err=angleWrap(target-player.a);turn=clamp(err/.75,-1,1);th=power*clamp(1-Math.abs(err)/1.65,.10,1);}}var keyAction=!!key.e,pressedKey=keyAction&&!lastKeyAction;lastKeyAction=keyAction;var pulse=actionPulse||pressedKey;actionPulse=false;return{turn:clamp(turn,-1,1),th:clamp(th,-1,1),boost:boost,analog:analog,target:target,power:power,action:pulse};}
function sx(x){return x-player.x+W/2;}function sy(y){return y-player.y+H/2;}
function update(dt){var c=controls(),acc=c.boost?180:108;player.a+=c.turn*(c.analog?3.15:2.45)*dt;player.vx+=Math.cos(player.a)*c.th*acc*dt;player.vy+=Math.sin(player.a)*c.th*acc*dt;player.vx*=Math.pow(.985,dt*60);player.vy*=Math.pow(.985,dt*60);var sp=hypot(player.vx,player.vy),mx=c.boost?255:178;if(sp>mx){player.vx*=mx/sp;player.vy*=mx/sp;}if(mode==='space'){player.x+=player.vx*dt;player.y+=player.vy*dt;}player.bank=lerp(player.bank,c.turn,.10);player.ox=lerp(player.ox,-player.vx*.035+c.turn*5,.09);player.oy=lerp(player.oy,-player.vy*.035,.09);near=null;for(var i=0;i<rocks.length;i++){var R=rocks[i];R.d.rot+=R.d.spin*dt;if(mode==='space'){var dx=player.x-R.x,dy=player.y-R.y,di=hypot(dx,dy),md=R.d.r+16;if(di<md&&di>.01){player.x+=dx/di*(md-di);player.y+=dy/di*(md-di);player.vx+=dx/di*18;player.vy+=dy/di*18;}}}for(i=0;i<planets.length;i++){var p=planets[i];if(hypot(player.x-p.x,player.y-p.y)<p.r+105)near=p;}for(i=0;i<traffic.length;i++){var n=traffic[i];n.a+=Math.sin(I.t*.6+i)*.09*dt;n.x+=Math.cos(n.a)*n.v*dt;n.y+=Math.sin(n.a)*n.v*dt;if(hypot(n.x,n.y)>950)n.a+=Math.PI;}if(c.action){if(mode==='space'&&near){landed=near;mode='landing';transition=0;}else if(mode==='landed'){mode='launch';transition=1;}}if(mode==='landing'){transition+=dt*1.7;if(transition>=1){transition=1;mode='landed';}}else if(mode==='launch'){transition-=dt*1.7;if(transition<=0){transition=0;mode='space';landed=null;}}}
function bg(){var q=new I.RNG(seed^0x773311);G.fillStyle='#070912';G.fillRect(0,0,W,H);for(var n=0;n<4;n++){var nx=(q.r(-500,500)-player.x*.13)+W/2,ny=(q.r(-360,360)-player.y*.13)+H/2,rad=q.r(230,420),col=q.p([[75,105,255],[66,205,166],[190,87,228],[244,126,93]]),gr=G.createRadialGradient(nx,ny,0,nx,ny,rad);gr.addColorStop(0,'rgba('+col.join(',')+',.09)');gr.addColorStop(1,'rgba('+col.join(',')+',0)');G.fillStyle=gr;G.beginPath();G.arc(nx,ny,rad,0,6.28);G.fill();}for(var i=0;i<stars.length;i++){var s=stars[i],x=sx(s.x*s.z),y=sy(s.y*s.z);if(x<0||y<0||x>W||y>H)continue;G.globalAlpha=.35+s.z*.6;G.fillStyle='#fff';G.fillRect(x,y,s.r,s.r);}G.globalAlpha=1;}
function radar(){var r=48,x=16+r,y=16+r;G.save();G.translate(x,y);G.fillStyle='rgba(8,11,19,.72)';G.beginPath();G.arc(0,0,r,0,6.28);G.fill();G.strokeStyle='#ddecff33';G.lineWidth=1.5;G.stroke();G.beginPath();G.arc(0,0,r*.62,0,6.28);G.stroke();G.beginPath();G.moveTo(-r,0);G.lineTo(r,0);G.moveTo(0,-r);G.lineTo(0,r);G.stroke();for(var i=0;i<planets.length;i++){var p=planets[i],px=(p.x-player.x)*.055,py=(p.y-player.y)*.055;if(hypot(px,py)<r-4){G.fillStyle=p.type===0?'#62e8bb':p.type===1?'#ffbd74':'#a7d7ff';G.beginPath();G.arc(px,py,3.5,0,6.28);G.fill();}}G.rotate(player.a);G.fillStyle='#fff';G.beginPath();G.moveTo(9,0);G.lineTo(-6,4);G.lineTo(-2,0);G.lineTo(-6,-4);G.fill();G.restore();}
function hud(){var compact=W<620,panW=compact?150:224;rr(W-panW-14,14,panW,72,14);G.fillStyle='rgba(8,11,19,.72)';G.fill();G.strokeStyle='#ffffff1d';G.stroke();G.fillStyle='#f3f7ff';G.font='700 15px sans-serif';G.fillText('INKSTAR',W-panW,37);G.font='11px sans-serif';G.fillStyle='#dbe6f0cc';G.fillText(Math.round(hypot(player.vx,player.vy))+' u/s',W-panW,56);if(!compact)G.fillText('seed '+seed,W-132,56);if(near&&mode==='space'){var w=Math.min(390,W-24),x=(W-w)/2,y=H-120;rr(x,y,w,70,16);G.fillStyle='rgba(9,12,20,.88)';G.fill();G.strokeStyle='#ffffff22';G.stroke();G.fillStyle=near.type===0?'#67edbe':near.type===1?'#ffc17c':'#b7dcff';G.font='700 20px sans-serif';G.fillText(near.name,x+16,y+28);G.fillStyle='#e3ecf6cc';G.font='12px sans-serif';G.fillText('Landable · tap/click LAND or press E',x+16,y+49);}}
function touchUI(){var U=ui(),cx=joy.on?joy.bx:U.joy.x,cy=joy.on?joy.by:U.joy.y,r=U.joy.r;G.save();G.globalAlpha=pointerSeen?.91:.78;G.fillStyle='#10141d72';G.strokeStyle='#ffffff35';G.lineWidth=2;G.beginPath();G.arc(cx,cy,r,0,6.28);G.fill();G.stroke();var kx=cx,ky=cy;if(joy.on){var dx=joy.x-joy.bx,dy=joy.y-joy.by,m=Math.min(r*.82,hypot(dx,dy)),a=Math.atan2(dy,dx);kx+=Math.cos(a)*m;ky+=Math.sin(a)*m;}G.beginPath();G.arc(kx,ky,r*.34,0,6.28);G.fillStyle='#ffffff16';G.fill();G.stroke();if(joy.on){G.strokeStyle='#8fe7ff88';G.lineWidth=3;G.beginPath();G.moveTo(cx,cy);G.lineTo(kx,ky);G.stroke();}function b(R,label,active){rr(R.x,R.y,R.w,R.h,13);G.fillStyle=active?'#5ccbea48':'#111620b8';G.fill();G.strokeStyle='#ffffff35';G.stroke();G.fillStyle='#fff';G.font='700 13px sans-serif';G.fillText(label,R.x+14,R.y+R.h*.62);}b(U.boost,'BOOST',anyBoost());b(U.act,mode==='landed'?'LAUNCH':'LAND',false);G.restore();}
function world(){bg();for(var i=0;i<planets.length;i++){var p=planets[i],x=sx(p.x),y=sy(p.y);if(x>-110&&y>-110&&x<W+110&&y<H+110)I.planet(G,p,x,y);}for(i=0;i<rocks.length;i++){var R=rocks[i],rx=sx(R.x),ry=sy(R.y);if(rx>-80&&ry>-80&&rx<W+80&&ry<H+80)I.rock(G,R.d,rx,ry);}for(i=0;i<traffic.length;i++){var n=traffic[i],nx=sx(n.x),ny=sy(n.y);if(nx>-80&&ny>-80&&nx<W+80&&ny<H+80)I.ship(G,n.d,nx,ny,n.a,.58,.35+.15*Math.sin(I.t*2+i),Math.sin(I.t+i)*.2);}I.ship(G,player.d,W/2+player.ox,H/2+player.oy,player.a,1,clamp(hypot(player.vx,player.vy)/170,0,1),player.bank);radar();hud();touchUI();}
function landing(){I.landscape(G,landed,W,H);G.fillStyle='rgba(4,8,15,.18)';G.fillRect(0,0,W,H);var cw=Math.min(W-24,760),ch=Math.min(142,H*.26),x=(W-cw)/2,y=H-ch-16;rr(x,y,cw,ch,20);G.fillStyle='rgba(10,14,22,.86)';G.fill();G.strokeStyle='#ffffff20';G.lineWidth=2;G.stroke();G.fillStyle=landed.type===0?'#68efc0':landed.type===1?'#ffc17c':'#b8dcff';G.font='700 '+(W<560?24:30)+'px sans-serif';G.fillText(landed.name,x+20,y+38);G.fillStyle='#e8eff7d8';G.font='13px sans-serif';G.fillText(landed.type===0?'Oceans, floating isles and humid green settlements.':landed.type===1?'Dust, salvage towers and hard orange light.':'Ice fields, aurora and a patient research outpost.',x+20,y+62);G.fillStyle='#ffffff10';rr(x+20,y+80,120,32,11);G.fill();rr(x+150,y+80,120,32,11);G.fill();G.fillStyle='#dce8f5cc';G.font='600 11px sans-serif';G.fillText(landed.type===1?'THREAT HIGH':'THREAT LOW',x+34,y+100);G.fillText(landed.type===0?'ECONOMY HIGH':'SERVICES BASIC',x+164,y+100);G.fillStyle='#fff';G.font='700 14px sans-serif';G.fillText('LANDING VISTA · tap/click LAUNCH or press E',x+20,y+128);touchUI();if(mode==='landing'||mode==='launch'){G.fillStyle='rgba(4,7,12,'+((1-transition)*.55)+')';G.fillRect(0,0,W,H);}}
function frame(ts){var dt=Math.min(.033,((ts-LAST)||16.7)/1000);LAST=ts;I.t+=dt;try{update(dt);if(mode==='space')world();else landing();if(first){first=false;BOOT.style.display='none';}}catch(e){BOOT.style.display='block';BOOT.textContent='Runtime error: '+(e&&e.message?e.message:e);return;}requestAnimationFrame(frame);}
requestAnimationFrame(frame);
})();